### ISSUE TITLE
QUESTION - Do You still recommend using this project or is it abandoned?

### ISSUE THREAD

**Issue by easysoft2k15** [fsprojects/FSharp.CloudAgent#13]
Due to the date of last commit I wonder if the project still is alive/usable.

**Comment by isaacabraham** [comment]
It's definitely still usable - indeed, a customer of mine is using a variant of this code base to process millions of messages every day since this repo was created.

However, it could be simplified now by delegating to things like azure web jobs or functions.

**Comment by isaacabraham** [comment]
But if you have any specific questions, let me know - HTH.

**Comment by easysoft2k15** [comment]
I Will.
Thank You very much!!
