### ISSUE TITLE
Move to fsprojects?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.CloudAgent#8]
Hi @isaacabraham  - since AzureStorageTypeProvider/ moved to http://github.com/fsprojects, would you like to move this there too?

cheers!
don

**Comment by isaacabraham** [comment]
Yes sure, same process as last time?

**Comment by dsyme** [comment]
Yep :)

**Comment by dsyme** [comment]
https://github.com/fsprojects-transfer

**Comment by isaacabraham** [comment]
Transferred. Also - I notice that the docs site is still under isaacabraham - will that change?

**Comment by fsgit** [comment]
Your transfer is complete! http://fsprojects.github.io/FSharp.CloudAgent/

**Comment by fsgit** [comment]
Please update https://github.com/fsprojects/FsProjectsAdmin/blob/master/BuildStatuses.md and any incoming links, e.g. those on http://fsharp.org (and search google for other incoming links)

**Comment by dsyme** [comment]
Somehow the docs for http://isaacabraham.github.io/FSharp.CloudAgent/ should come down, not sure why they stay up.  Perhaps GitHub will get rid of them in due course.
